import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"
import StoreProvider from "@/redux/StoreProvider";
import { store } from "@/redux/store";
import { AudioPlayerProvider } from "./context/AudioPlayerContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <AudioPlayerProvider>
            {children}
          </AudioPlayerProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
