import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";

import { AudioPlayerProvider } from "./context/AudioPlayerContext";
import SignupModal from "./compoments/modals/SignupModal";
import LogInModal from "./compoments/modals/LogInModal";
import ForgotPassword from "./compoments/modals/ForgotPassword";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hollywood Ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <AudioPlayerProvider>
            {children}
            <SignupModal />
            <LogInModal />
            <ForgotPassword />
          </AudioPlayerProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
